@baseUrl = http://localhost:3000

### Obtener todas las carreras
GET {{baseUrl}}/carreras


### Crear una carrera
POST {{baseUrl}}/carreras
Content-Type: application/json

{
  "nombreCarrera": "Ingenieria en minecraft",
  "duracionCarrera": 5
}

### Obtener una carrera por id
GET {{baseUrl}}/carreras/22

### Actualizar una carrera
PUT {{baseUrl}}/carreras/22
Content-Type: application/json

{
  "nombreCarrera": "Ingeniería en minecraft 20",
  "duracionCarrera": 1
}

### Eliminar una carrera
DELETE {{baseUrl}}/carreras/24