<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { RouterLink, useRoute, useRouter } from 'vue-router'
import AdminFilters from '../components/AdminFilters.vue'
import AdminPagination from '../components/AdminPagination.vue'
import AdminState from '../components/AdminState.vue'
import AdminTable from '../components/AdminTable.vue'
import { adminApi } from '../api/adminApi'
import { periodSchema } from '../schemas/adminSchemas'
import type { Career, EnrollmentPeriod, Subject } from '../types/admin'
import { useFeedback } from '@/ui/feedback'
import { academicLabel, formatAcademicDate } from '@/core/presentation/academicLabels'

const route = useRoute(); const router = useRouter(); const feedback = useFeedback()
const periods = ref<EnrollmentPeriod[]>([]); const careers = ref<Career[]>([]); const subjectsByYear = ref<Array<{ anio: number | null; materias: Subject[] }>>([]); const selected = ref<EnrollmentPeriod | null>(null)
const loading = ref(false); const error = ref(''); const saving = ref(false); const pagination = ref({ page: 1, limit: 20, total: 0, totalPages: 0 }); const cycle = ref(String(route.query.cicloLectivo ?? ''))
const form = reactive<Record<string, any>>({ tipo: 'MATERIA', cicloLectivo: new Date().getFullYear(), fechaInicio: '', fechaFin: '', materiasIds: [], descripcion: '' }); const careerId = ref<number | null>(null); const fieldError = ref('')
const mode = computed(() => String(route.name)); const isList = computed(() => mode.value === 'admin-periods'); const isDetail = computed(() => mode.value === 'admin-period-detail'); const id = computed(() => Number(route.params.id))
async function loadCareers() { try { careers.value = (await adminApi.listCareers({ limit: 100 })).data } catch { careers.value = [] } }
async function loadList() { loading.value = true; error.value = ''; try { const result = await adminApi.listPeriods({ cicloLectivo: cycle.value ? Number(cycle.value) : undefined, page: Number(route.query.page ?? 1) }); periods.value = result.data; pagination.value = result.pagination } catch { error.value = 'No pudimos cargar los períodos.' } finally { loading.value = false } }
async function loadDetail() { loading.value = true; error.value = ''; try { selected.value = await adminApi.getPeriod(id.value) } catch { error.value = 'No pudimos cargar el período.' } finally { loading.value = false } }
async function loadSubjects() { if (!careerId.value) { subjectsByYear.value = []; return }; try { subjectsByYear.value = await adminApi.getSubjectsByYear(careerId.value) } catch { subjectsByYear.value = [] } }
function toggleSubject(subjectId: number) { form.materiasIds = form.materiasIds.includes(subjectId) ? form.materiasIds.filter((value: number) => value !== subjectId) : [...form.materiasIds, subjectId] }
function apply() { void router.replace({ query: { cicloLectivo: cycle.value || undefined, page: undefined } }).then(loadList) }
function reset() { Object.assign(form, { tipo: 'MATERIA', cicloLectivo: new Date().getFullYear(), fechaInicio: '', fechaFin: '', materiasIds: [], descripcion: '' }); careerId.value = null; fieldError.value = ''; if (mode.value === 'admin-period-edit') void adminApi.getPeriod(id.value).then(period => Object.assign(form, { cicloLectivo: period.cicloLectivo, fechaInicio: period.fechaInicio.slice(0, 10), fechaFin: period.fechaFin.slice(0, 10), materiasIds: (period.materias ?? []).map((item: any) => item.materiaId ?? item.id), descripcion: period.descripcion ?? '' })) }
async function save() { fieldError.value = ''; const result = periodSchema.safeParse(form); if (!result.success) { fieldError.value = result.error.issues[0]?.message ?? 'Revisá los datos.'; return }; saving.value = true; try { const payload = { ...result.data, fechaInicio: new Date(`${result.data.fechaInicio}T00:00:00.000Z`).toISOString(), fechaFin: new Date(`${result.data.fechaFin}T23:59:59.000Z`).toISOString() }; if (mode.value === 'admin-period-create') await adminApi.createPeriod(payload); else await adminApi.updatePeriod(id.value, payload); feedback.success(mode.value === 'admin-period-create' ? 'Período creado.' : 'Período actualizado.'); await router.replace({ name: 'admin-periods' }) } catch { feedback.error('No se pudo guardar el período.') } finally { saving.value = false } }
async function deactivate() { if (!selected.value || !window.confirm('¿Desactivar este período?')) return; try { await adminApi.deactivatePeriod(selected.value.id); feedback.success('Período desactivado.'); await router.replace({ name: 'admin-periods' }) } catch { feedback.error('No se pudo desactivar el período.') } }
watch(careerId, () => void loadSubjects()); onMounted(() => { void loadCareers(); if (isList.value) void loadList(); else if (isDetail.value) void loadDetail(); else reset() }); watch(() => route.fullPath, () => { if (isList.value) void loadList(); else if (isDetail.value) void loadDetail(); else reset() })
</script>

<template>
  <main aria-labelledby="admin-periods-title" class="mx-auto max-w-6xl">
    <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-semibold uppercase tracking-[0.14em] text-[var(--color-brand)]">Administración</p><h1 id="admin-periods-title" class="mt-2 text-3xl font-semibold">Períodos de inscripción</h1></div><RouterLink v-if="isList" :to="{ name: 'admin-period-create' }" class="min-h-11 rounded-lg bg-[var(--color-brand)] px-4 py-2.5 font-semibold text-white">Nuevo período</RouterLink></div>
    <template v-if="isList"><form class="mt-6 flex max-w-md items-end gap-3 rounded-xl border border-[var(--color-border)] bg-white p-4" @submit.prevent="apply"><label class="flex-1 text-sm font-semibold">Ciclo lectivo<input v-model="cycle" inputmode="numeric" class="admin-input" /></label><button class="min-h-11 rounded-lg bg-[var(--color-brand)] px-4 font-semibold text-white">Aplicar</button></form><div class="mt-5"><AdminState :loading="loading" :error="error" :empty="!loading && !error && !periods.length" empty-text="No hay períodos para mostrar." @retry="loadList"><AdminTable :columns="[{ key: 'type', label: 'Tipo' }, { key: 'cycle', label: 'Ciclo' }, { key: 'dates', label: 'Vigencia' }, { key: 'status', label: 'Estado' }]"><template #rows><tr v-for="period in periods" :key="period.id" class="border-t border-[var(--color-border)]"><td class="px-4 py-3"><RouterLink :to="{ name: 'admin-period-detail', params: { id: period.id } }" class="font-semibold text-[var(--color-brand)]">{{ academicLabel(period.tipo) }}</RouterLink><span v-if="period.tipo === 'EXAMEN'" class="ml-2 rounded-full bg-[#f6f7f4] px-2 py-1 text-xs">Informativo</span></td><td class="px-4 py-3">{{ period.cicloLectivo }}</td><td class="px-4 py-3">{{ formatAcademicDate(period.fechaInicio) }} → {{ formatAcademicDate(period.fechaFin) }}</td><td class="px-4 py-3">{{ academicLabel(period.activo ? 'ACTIVA' : 'INACTIVA') }}</td><td class="px-4 py-3 text-right"><RouterLink v-if="period.tipo === 'MATERIA'" :to="{ name: 'admin-period-edit', params: { id: period.id } }" class="font-semibold text-[var(--color-brand)]">Editar</RouterLink></td></tr></template><template #cards><article v-for="period in periods" :key="period.id" class="rounded-lg border border-[var(--color-border)] p-4"><RouterLink :to="{ name: 'admin-period-detail', params: { id: period.id } }" class="font-semibold text-[var(--color-brand)]">{{ academicLabel(period.tipo) }}</RouterLink><p class="text-sm text-[var(--color-graphite)]">{{ period.cicloLectivo }} · {{ formatAcademicDate(period.fechaInicio) }} → {{ formatAcademicDate(period.fechaFin) }}</p></article></template></AdminTable><AdminPagination :pagination="pagination" @change="(page) => router.replace({ query: { ...route.query, page: String(page) } }).then(loadList)" /></AdminState></div></template>
    <template v-else-if="isDetail"><AdminState :loading="loading" :error="error" @retry="loadDetail"><section v-if="selected" class="mt-7 rounded-xl border border-[var(--color-border)] bg-white p-6"><div class="flex flex-wrap items-start justify-between gap-4"><div><h2 class="text-2xl font-semibold">Período {{ academicLabel(selected.tipo) }}</h2><p class="text-[var(--color-graphite)]">Ciclo {{ selected.cicloLectivo }} · {{ formatAcademicDate(selected.fechaInicio) }} → {{ formatAcademicDate(selected.fechaFin) }}</p></div><div class="flex gap-2"><RouterLink v-if="selected.tipo === 'MATERIA'" :to="{ name: 'admin-period-edit', params: { id: selected.id } }" class="min-h-10 rounded-lg bg-[var(--color-brand)] px-4 py-2 font-semibold text-white">Editar</RouterLink><button v-if="selected.tipo === 'MATERIA'" type="button" class="min-h-10 rounded-lg border border-[var(--color-border)] px-4 py-2" @click="deactivate">Desactivar</button></div></div><p v-if="selected.tipo === 'EXAMEN'" class="mt-5 rounded-lg bg-[#f6f7f4] p-4 text-sm">Los períodos EXAMEN existentes se muestran solo como información. Su gestión se habilitará junto con Mesas de examen.</p><h3 class="mt-7 text-xl font-semibold">Materias habilitadas</h3><ul class="mt-3 grid gap-2 sm:grid-cols-2"><li v-for="item in selected.materias ?? []" :key="(item as any).materiaId ?? (item as any).id" class="rounded-lg bg-[#f6f7f4] p-3">{{ (item as any).materia?.nombre ?? (item as any).nombre }}</li></ul></section></AdminState></template>
    <template v-else><section class="mt-7 max-w-3xl rounded-xl border border-[var(--color-border)] bg-white p-6"><h2 class="text-2xl font-semibold">{{ mode === 'admin-period-create' ? 'Nuevo período de materias' : 'Editar período de materias' }}</h2><form class="mt-5 grid gap-4 sm:grid-cols-2" @submit.prevent="save"><label class="font-semibold">Ciclo lectivo<input v-model.number="form.cicloLectivo" type="number" class="admin-input" /></label><div></div><label class="font-semibold">Fecha inicial<input v-model="form.fechaInicio" type="date" class="admin-input" /></label><label class="font-semibold">Fecha final<input v-model="form.fechaFin" type="date" class="admin-input" /></label><label class="font-semibold sm:col-span-2">Carrera<select v-model.number="careerId" class="admin-input"><option :value="null">Seleccionar carrera</option><option v-for="career in careers" :key="career.id" :value="career.id">{{ career.nombre }}</option></select></label><fieldset class="sm:col-span-2"><legend class="font-semibold">Materias habilitadas</legend><p class="mt-1 text-sm text-[var(--color-graphite)]">Seleccioná una carrera y luego las materias por año.</p><div v-for="group in subjectsByYear" :key="String(group.anio)" class="mt-3 rounded-lg border border-[var(--color-border)] p-3"><h3 class="font-semibold">{{ group.anio ?? 'Sin año' }}° año</h3><label v-for="subject in group.materias" :key="subject.id" class="mt-2 flex items-center gap-2 text-sm"><input type="checkbox" :checked="form.materiasIds.includes(subject.id)" @change="toggleSubject(subject.id)" />{{ subject.nombre }}</label></div></fieldset><label class="font-semibold sm:col-span-2">Descripción<textarea v-model="form.descripcion" class="admin-input min-h-20"></textarea></label><p v-if="fieldError" class="field-error sm:col-span-2" role="alert">{{ fieldError }}</p><div class="flex gap-3 sm:col-span-2"><button type="submit" class="min-h-11 rounded-lg bg-[var(--color-brand)] px-5 font-semibold text-white" :disabled="saving">{{ saving ? 'Guardando…' : 'Guardar período' }}</button><RouterLink :to="{ name: 'admin-periods' }" class="min-h-11 rounded-lg border border-[var(--color-border)] px-5 py-2.5">Cancelar</RouterLink></div></form></section></template>
  </main>
</template>

<style scoped>.admin-input{margin-top:.25rem;min-height:2.75rem;width:100%;border:1px solid var(--color-border);border-radius:.5rem;padding:0 .75rem;font-weight:400}.field-error{font-size:.875rem;color:#a31118}</style>
