<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { RouterLink, useRoute, useRouter } from 'vue-router'
import AdminFilters from '../components/AdminFilters.vue'; import AdminPagination from '../components/AdminPagination.vue'; import AdminState from '../components/AdminState.vue'; import AdminTable from '../components/AdminTable.vue'
import { adminApi } from '../api/adminApi'; import { careerSchema } from '../schemas/adminSchemas'; import type { Career } from '../types/admin'; import { useFeedback } from '@/ui/feedback'
const route=useRoute(); const router=useRouter(); const feedback=useFeedback(); const careers=ref<Career[]>([]); const selected=ref<Career|null>(null); const loading=ref(false); const error=ref(''); const saving=ref(false); const search=ref(String(route.query.search??'')); const active=ref(String(route.query.activo??'')); const pagination=ref({page:1,limit:20,total:0,totalPages:0}); const form=reactive({nombre:'',duracionAnios:4}); const fieldError=ref('');
const mode=computed(()=>String(route.name)); const isList=computed(()=>mode.value==='admin-careers'); const isDetail=computed(()=>mode.value==='admin-career-detail'); const isForm=computed(()=>mode.value==='admin-career-create'||mode.value==='admin-career-edit'); const id=computed(()=>Number(route.params.id));
const groupedPlan = computed(() => { const groups = new Map<number, Career['materias']>(); for (const subject of selected.value?.materias ?? []) { const year = subject.curso?.anio ?? 0; groups.set(year, [...(groups.get(year) ?? []), subject]) }; return [...groups.entries()].sort(([a], [b]) => a - b) })
async function loadList(){loading.value=true;error.value='';try{const result=await adminApi.listCareers({search:search.value||undefined,activo:active.value===''?undefined:active.value==='true',page:Number(route.query.page??1)});careers.value=result.data;pagination.value=result.pagination}catch{error.value='No pudimos cargar las carreras.'}finally{loading.value=false}}
async function loadDetail(){loading.value=true;error.value='';try{selected.value=await adminApi.getCareerPlan(id.value)}catch{error.value='No pudimos cargar la carrera.'}finally{loading.value=false}}
function apply(){void router.replace({query:{search:search.value||undefined,activo:active.value||undefined,page:undefined}}).then(loadList)}
function reset(){form.nombre='';form.duracionAnios=4;fieldError.value='';if(isDetail.value||mode.value==='admin-career-edit')void loadDetail()}
async function save(){fieldError.value='';const result=careerSchema.safeParse(form);if(!result.success){fieldError.value=result.error.issues[0]?.message??'Revisá los datos.';return}saving.value=true;try{if(mode.value==='admin-career-create'){await adminApi.createCareer({nombre:result.data.nombre,duracionAnios:result.data.duracionAnios});feedback.success('Carrera creada.')}else{await adminApi.updateCareer(id.value,result.data);feedback.success('Carrera actualizada.')}await router.replace({name:'admin-careers'})}catch{feedback.error('No se pudo guardar la carrera.')}finally{saving.value=false}}
async function deactivate(){if(!selected.value||!window.confirm('¿Desactivar esta carrera?'))return;try{await adminApi.deactivateCareer(selected.value.id);feedback.success('Carrera desactivada.');await router.replace({name:'admin-careers'})}catch{feedback.error('No se pudo desactivar la carrera.')}}
onMounted(()=>{if(isList.value)void loadList();else if(isDetail.value)void loadDetail();else reset()});watch(()=>route.fullPath,()=>{if(isList.value)void loadList();else if(isDetail.value)void loadDetail();else reset()})
</script>
<template><main aria-labelledby="admin-careers-title" class="mx-auto max-w-6xl"><div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-semibold uppercase tracking-[0.14em] text-[var(--color-brand)]">Administración</p><h1 id="admin-careers-title" class="mt-2 text-3xl font-semibold">Carreras</h1></div><RouterLink v-if="isList" :to="{name:'admin-career-create'}" class="min-h-11 rounded-lg bg-[var(--color-brand)] px-4 py-2.5 font-semibold text-white">Nueva carrera</RouterLink></div>
<template v-if="isList"><AdminFilters v-model:search="search" placeholder="Nombre de carrera" @submit="apply"><label class="text-sm font-semibold">Estado<select v-model="active" class="mt-1 min-h-11 w-full rounded-lg border border-[var(--color-border)] px-3 font-normal"><option value="">Todos</option><option value="true">Activas</option><option value="false">Inactivas</option></select></label></AdminFilters><div class="mt-5"><AdminState :loading="loading" :error="error" :empty="!loading&&!error&&!careers.length" empty-text="No hay carreras para mostrar." @retry="loadList"><AdminTable :columns="[{key:'name',label:'Carrera'},{key:'years',label:'Duración'},{key:'status',label:'Estado'}]"><template #rows><tr v-for="career in careers" :key="career.id" class="border-t border-[var(--color-border)]"><td class="px-4 py-3"><RouterLink :to="{name:'admin-career-detail',params:{id:career.id}}" class="font-semibold text-[var(--color-brand)]">{{career.nombre}}</RouterLink></td><td class="px-4 py-3">{{career.duracionAnios}} años</td><td class="px-4 py-3">{{career.activo?'Activa':'Inactiva'}}</td><td class="px-4 py-3 text-right"><RouterLink :to="{name:'admin-career-edit',params:{id:career.id}}" class="font-semibold text-[var(--color-brand)]">Editar</RouterLink></td></tr></template><template #cards><article v-for="career in careers" :key="career.id" class="rounded-lg border border-[var(--color-border)] p-4"><RouterLink :to="{name:'admin-career-detail',params:{id:career.id}}" class="font-semibold text-[var(--color-brand)]">{{career.nombre}}</RouterLink><p class="text-sm text-[var(--color-graphite)]">{{career.duracionAnios}} años · {{career.activo?'Activa':'Inactiva'}}</p></article></template></AdminTable><AdminPagination :pagination="pagination" @change="(page)=>router.replace({query:{...route.query,page:String(page)}}).then(loadList)"/></AdminState></div></template>
<template v-else-if="isDetail"><AdminState :loading="loading" :error="error" @retry="loadDetail"><section v-if="selected" class="mt-7 rounded-xl border border-[var(--color-border)] bg-white p-6"><div class="flex flex-wrap items-start justify-between gap-4"><div><h2 class="text-2xl font-semibold">{{selected.nombre}}</h2><p class="text-[var(--color-graphite)]">{{selected.duracionAnios}} años · {{selected.activo?'Activa':'Inactiva'}}</p></div><div class="flex gap-3"><RouterLink :to="{name:'admin-career-edit',params:{id:selected.id}}" class="min-h-10 rounded-lg bg-[var(--color-brand)] px-4 py-2 font-semibold text-white">Editar</RouterLink><button type="button" class="min-h-10 rounded-lg border border-[var(--color-border)] px-4 py-2" @click="deactivate">Desactivar</button></div></div><h3 class="mt-8 text-xl font-semibold">Plan de estudio por año</h3><div v-if="groupedPlan.length" class="mt-3 space-y-4"><section v-for="[year, subjects] in groupedPlan" :key="year"><h4 class="font-semibold">{{year || 'Sin año'}}° año</h4><div class="mt-2 grid gap-3 sm:grid-cols-2"><div v-for="subject in subjects" :key="subject.id" class="rounded-lg bg-[#f6f7f4] p-4"><RouterLink :to="{name:'admin-subject-detail',params:{id:subject.id}}" class="font-semibold text-[var(--color-brand)]">{{subject.nombre}}</RouterLink><span class="block text-sm text-[var(--color-graphite)]">{{subject.cargaHoraria}} h</span></div></div></section></div><p v-else class="mt-3 text-[var(--color-graphite)]">No hay materias cargadas todavía.</p><RouterLink :to="{name:'admin-subject-create',query:{carreraId:selected.id}}" class="mt-5 inline-flex min-h-10 items-center rounded-lg border border-[var(--color-brand)] px-4 py-2 font-semibold text-[var(--color-brand)]">Agregar materia a esta carrera</RouterLink></section></AdminState></template>
<template v-else><section class="mt-7 max-w-2xl rounded-xl border border-[var(--color-border)] bg-white p-6"><h2 class="text-2xl font-semibold">{{mode==='admin-career-create'?'Nueva carrera':'Editar carrera'}}</h2><form class="mt-5 grid gap-4" @submit.prevent="save"><label class="font-semibold">Nombre<input v-model="form.nombre" class="admin-input" /></label><label class="font-semibold">Duración en años<input v-model.number="form.duracionAnios" type="number" min="1" max="10" class="admin-input" /></label><p v-if="fieldError" class="field-error" role="alert">{{fieldError}}</p><div class="flex gap-3"><button type="submit" class="min-h-11 rounded-lg bg-[var(--color-brand)] px-5 font-semibold text-white" :disabled="saving">{{saving?'Guardando…':'Guardar carrera'}}</button><RouterLink :to="{name:isForm&&mode==='admin-career-edit'?'admin-career-detail':'admin-careers',params:mode==='admin-career-edit'?{id}:undefined}" class="min-h-11 rounded-lg border border-[var(--color-border)] px-5 py-2.5">Cancelar</RouterLink></div></form></section></template></main></template>
<style scoped>.admin-input{margin-top:.25rem;min-height:2.75rem;width:100%;border:1px solid var(--color-border);border-radius:.5rem;padding:0 .75rem;font-weight:400}.field-error{font-size:.875rem;color:#a31118}</style>
